### ISSUE TITLE
Unable to use with appsody applications in vscode

### ISSUE THREAD

**Issue by csantanapr** [eclipse/codewind-node-profiler#5]
Using VSCode Codewind node.js profiler with appsody app it doesn't highlights the code with profiling metadata

Steps to reproduce:
- create appsody app
```
appsody init nodejs-express
```
- Add app to codewind workspace
- Right click on app select `Open Performance Dashboard`
- Run a Load Test
- Verify files are generated in root directory
```
tree load-test                                 
load-test
├── 20190923221512
│   ├── metrics.json
│   └── profiling.json
├── 20190923221649
│   ├── metrics.json
│   └── profiling.json
└── config.json
```
- Open `app.js` go to line 3 and 4
```
const app = require('express')()

app.get('/', (req, res) => {
  res.send("Hello from Appsody!");
});

module.exports.app = app;
```

Problem:
No performance/profiling metada shows up

I think it doesn't work because the profile file `load-test/###/profiling.json` has the file path starting in `/project/user-app/app.js` and the `/parent/user-app` doesn't exist in the appsody root directory for the app locally in vscode
```
      {
        "self": 1702,
        "parent": 1701,
        "file": "/project/user-app/app.js",
        "name": "app.get",
        "line": 3,
        "count": 3
      },
```
The root of the appsody app only contains `app.js` and `package.json`

**Comment by csantanapr** [comment]
I tried replacing `/project/user-app/app.js` with `/app.js` in all the `profiling.json` files, and I still don't get any metadata when open app.js and hover the mouse or put the cursor on lines 3 or 4

**Comment by tetchel** [comment]
Issue moved to [eclipse/codewind #533](https://github.com/eclipse/codewind/issues/533) via [**ZenHub**](https://www.zenhub.com/)
